// release/ReleaseReporter.js - Generates release readiness reports
import { writeFileSync, mkdirSync, existsSync, readdirSync, readFileSync } from 'fs';
import { join } from 'path';

function reportsDir(workspaceRoot) {
  return join(workspaceRoot, '.local-agent', 'reports');
}

function icon(check) {
  if (check.passed === true)  return '✓';
  if (check.passed === false) return check.severity === 'FAIL' ? '✗' : '⚠';
  return '–';
}

export function generateReport(workspaceRoot, checkResult) {
  const dir = reportsDir(workspaceRoot);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const ts      = new Date().toISOString();
  const slug    = ts.replace(/[:.]/g, '-');
  const mdPath  = join(dir, `release-readiness-${slug}.md`);
  const jsonPath = join(dir, `release-readiness-${slug}.json`);

  const { checks, result, failCount, warnCount, infoCount, blockers, recommendations, projectName } = checkResult;

  const resEmoji = result === 'PASS' ? '✅' : result === 'WARNING' ? '⚠️' : '❌';

  const md = [
    `# Release Readiness Report`,
    `**Date**: ${ts}`,
    `**Project**: ${projectName ?? 'Unknown'}`,
    `**Result**: ${resEmoji} ${result}`,
    '',
    '## Summary',
    `| Metric | Count |`,
    `|--------|-------|`,
    `| Total checks | ${checks.length} |`,
    `| Passed | ${checks.filter((c) => c.passed === true).length} |`,
    `| Warnings | ${warnCount} |`,
    `| Failed | ${failCount} |`,
    '',
  ];

  if (blockers.length) {
    md.push('## 🚫 Blockers (must fix before release)');
    for (const c of blockers) {
      md.push(`### ✗ ${c.name}`);
      md.push(c.message);
      if (c.details.length) { md.push(''); md.push('**Details:**'); c.details.forEach((d) => md.push(`- ${d}`)); }
      if (c.suggestions.length) { md.push(''); md.push('**How to fix:**'); c.suggestions.forEach((s) => md.push(`- ${s}`)); }
      md.push('');
    }
  }

  const warnings = checks.filter((c) => c.passed === false && c.severity === 'WARN');
  if (warnings.length) {
    md.push('## ⚠ Warnings (recommended to fix)');
    for (const c of warnings) {
      md.push(`### ⚠ ${c.name}`);
      md.push(c.message);
      if (c.details.length)     { c.details.slice(0,3).forEach((d) => md.push(`- ${d}`)); }
      if (c.suggestions.length) { md.push(''); c.suggestions.forEach((s) => md.push(`> ${s}`)); }
      md.push('');
    }
  }

  md.push('## Checks Detail');
  for (const c of checks) {
    md.push(`### ${icon(c)} ${c.name} — ${c.passed === true ? 'PASS' : c.passed === false ? c.severity : 'INFO'}`);
    md.push(`**Category**: ${c.category}`);
    md.push(c.message);
    if (c.details.length) c.details.slice(0,5).forEach((d) => md.push(`  - ${d}`));
    md.push('');
  }

  if (recommendations.length) {
    md.push('## Recommendations');
    recommendations.forEach((r) => md.push(`- ${r}`));
    md.push('');
  }

  md.push('---');
  md.push('*Generated by local-agent release-check — fully offline, no deploy.*');

  writeFileSync(mdPath,  md.join('\n'));
  writeFileSync(jsonPath, JSON.stringify({ ...checkResult, generatedAt: ts }, null, 2));

  const summary = { result, failCount, warnCount, blockersCount: blockers.length, recommendationsCount: recommendations.length };
  return { mdPath, jsonPath, summary };
}

export function getLatestReport(workspaceRoot) {
  const dir = reportsDir(workspaceRoot);
  if (!existsSync(dir)) return null;
  const reports = readdirSync(dir)
    .filter((f) => f.startsWith('release-readiness-') && f.endsWith('.json'))
    .sort().reverse();
  if (!reports.length) return null;
  try { return JSON.parse(readFileSync(join(dir, reports[0]), 'utf8')); } catch { return null; }
}

export function listReports(workspaceRoot) {
  const dir = reportsDir(workspaceRoot);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.startsWith('release-readiness-') && f.endsWith('.json'))
    .sort().reverse()
    .map((f) => {
      try {
        const r = JSON.parse(readFileSync(join(dir, f), 'utf8'));
        return { filename: f, result: r.result, failCount: r.failCount, warnCount: r.warnCount, generatedAt: r.generatedAt };
      } catch { return { filename: f }; }
    });
}
