// core/workspace.js - workspace manager for .local-agent directory
import { existsSync, mkdirSync, writeFileSync, statSync } from 'fs';
import { join, resolve } from 'path';

const WORKSPACE_DIR = '.local-agent';

const SUBDIRS = [
  'backups',
  'patches',
  'logs',
  'memory',
  'reports',
  'index',
];

const INITIAL_SUMMARY_TEMPLATE = `# Project Summary

> Generated by local-agent. Update this file with project-specific notes.

## Overview

_Not yet scanned. Run \`local-agent scan\` to populate._

## Architecture

_TBD_

## Key Directories

_TBD_

## Build & Test Commands

_TBD_

## Notes

_TBD_
`;

/**
 * Initialize the .local-agent workspace inside a target project directory.
 * Creates the directory tree and writes a placeholder project-summary.md.
 *
 * @param {string} targetDir - Absolute path to the project root
 * @returns {{ workspaceDir: string, created: boolean }}
 */
export function initWorkspace(targetDir) {
  const abs = resolve(targetDir);

  if (!existsSync(abs)) {
    throw new Error(`Target directory does not exist: ${abs}`);
  }

  const stat = statSync(abs);
  if (!stat.isDirectory()) {
    throw new Error(`Target path is not a directory: ${abs}`);
  }

  const workspaceDir = join(abs, WORKSPACE_DIR);
  const alreadyExisted = existsSync(workspaceDir);

  // Create workspace root
  if (!alreadyExisted) {
    mkdirSync(workspaceDir, { recursive: true });
  }

  // Create standard subdirectories
  for (const sub of SUBDIRS) {
    const subPath = join(workspaceDir, sub);
    if (!existsSync(subPath)) {
      mkdirSync(subPath, { recursive: true });
    }
  }

  // Write initial project summary placeholder if it doesn't exist
  const summaryPath = join(workspaceDir, 'project-summary.md');
  if (!existsSync(summaryPath)) {
    writeFileSync(summaryPath, INITIAL_SUMMARY_TEMPLATE, 'utf8');
  }

  // Write a .gitignore inside .local-agent to avoid committing logs/index
  const gitignorePath = join(workspaceDir, '.gitignore');
  if (!existsSync(gitignorePath)) {
    const gitignoreContent = [
      '# local-agent internal files — do not commit',
      'logs/',
      'index/',
      'memory/',
      'backups/',
      'patches/',
      'reports/',
      '*.tmp',
    ].join('\n') + '\n';
    writeFileSync(gitignorePath, gitignoreContent, 'utf8');
  }

  return {
    workspaceDir,
    created: !alreadyExisted,
  };
}

/**
 * Returns an object with all standard paths inside the workspace.
 *
 * @param {string} targetDir - Absolute path to the project root
 * @returns {Record<string, string>}
 */
export function getWorkspacePaths(targetDir) {
  const abs = resolve(targetDir);
  const workspaceDir = join(abs, WORKSPACE_DIR);

  return {
    root: abs,
    workspace: workspaceDir,
    config: join(workspaceDir, 'config.json'),
    summary: join(workspaceDir, 'project-summary.md'),
    projectMap: join(workspaceDir, 'project-map.json'),
    logs: join(workspaceDir, 'logs'),
    logFile: join(workspaceDir, 'logs', 'agent.log'),
    memory: join(workspaceDir, 'memory'),
    index: join(workspaceDir, 'index'),
    reports: join(workspaceDir, 'reports'),
    backups: join(workspaceDir, 'backups'),
    patches: join(workspaceDir, 'patches'),
  };
}

/**
 * Check whether a workspace has already been initialized in a directory.
 *
 * @param {string} targetDir
 * @returns {boolean}
 */
export function isWorkspaceInitialized(targetDir) {
  const abs = resolve(targetDir);
  return existsSync(join(abs, WORKSPACE_DIR));
}
